services:
  app:
    build: .
    ports:
      - "5005:5000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/reading_list

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: reading_list
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
